spring:
  application:
    name: cliente-api

  datasource:
    url: jdbc:postgresql://localhost:5432/clientedb
    username: postgres
    password: 1868
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: "ClienteApiJwtSecretKeyParaAutenticacaoSegura2026!@#$%MuitoSegura"
    expiration: 3600000

  viacep:
    url: https://viacep.com.br/ws

logging:
  level:
    com.seunome.clienteapi: DEBUG
    org.springframework.security: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

server:
  port: 8080